included:
  - Sources
  - Tests
disabled_rules:
    - file_length
    - force_cast
    - function_parameter_count
    - todo
    - type_body_length

line_length:
    warning: 160
    ignores_comments: true
    ignores_interpolated_strings: true
nesting:
    type_level: 2
identifier_name:
    excluded:
        - id
trailing_comma:
    mandatory_comma: true
type_name:
    excluded:
        - T
